### PR TITLE
Add Android support for KUtrace

### PR DESCRIPTION
**Pull request by k-sareen**
This commit adds support for running KUtrace on Android. Build and setup instructions are described in linux/android/README.md. This commit also fixes some bugs in the postprocessing such as assuming 32-bit time counters for ARM64.

Two sets of patches are added: with and without kernel ABI changes. The patches without ABI changes should apply cleaner to kernel versions which don't match the ones specified in the README.

This commit also improves the base40.cc program to print delimiting pairs of labels.

### CODE REVIEW

**Comment by k-sareen** [comment]
This PR makes some changes to the common post-processing. If you're worried that it might break support for some other platform, then let me know and we can figure out how to work around it.

EDIT: I also have a branch [here](https://github.com/k-sareen/KUtrace/tree/directory-restructure) that restructures the entire repository to reduce code duplication. We can rebase and merge that branch after merging this PR.

**Review by dicksites — APPROVED** [review]
I looked at all but the largest file, linux/android/aosp-without-abi-change.patch, which I would not understand anyway. All looks good.

**Comment by dicksites** [comment]
Wow. Kunal, many thanks for pulling all this together. I looked at all the
diffs except the 30K-line patch file and it all looks excellent. Approved.

I have never done a github change approval before, so I don't know if I
have done every necessary step. Please let me know if there is more for me
to do.

Thanks, /dick

**Comment by k-sareen** [comment]
Did you mean `linux/android/aosp.patch`? That's the one with the changes to the XML ABI. `linux/android/aosp-without-abi-changes.patch` should be a small-ish patch with just the changes we made to add KUtrace markers to the kernel.

EDIT: If everything looks good then you can merge the PR using the "Merge pull request" button below.

**Comment by dicksites** [comment]
Yes, aosp.patch. My mistake (off by one line). If this file needs another
pair of eyes to look at it, Sara might be best.
/dick

**Comment by k-sareen** [comment]
No it's fine. The XML changes are auto-generated so no one would really understand it. The XML changes are for the kernel symbol CRCs. `aosp.patch` is just the XML ABI change + ABI file change + `aosp-without-abi-changes.patch`.

**Pull request merged**
